### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by F3F5** [2lstudios-mc/RedstoneLimiter#2]
If the player does as in the screenshot, he plants automatically (because the seeds are there), and the observer works very quickly, and the redstone limiter blocks it. So, if I allow more values, then there will be lag machines. Screenshot: https://prnt.sc/lfhlBYr6VGDv 

Without thix fix because all needs to observer 🤙

**Comment by linsaftw** [comment]
Make redstone limiter threshold different depending on the block activated.

**Comment by F3F5** [comment]
> (Make redstone limiter threshold different depending on the block activated) would fix the issue.

yes, better than NOTHING

**Comment by linsaftw** [comment]
Was not related to RedstoneLimiter.
